#!/usr/bin/env bash
# Regenerate agent-loop/dashboard.md from real filesystem state.
# Sources of truth (never hand-maintained):
#   - orchestrator/inbox/*.md          -> Queued
#   - pipelines/*/runs/*/ (no eval.md) -> Running
#   - pipelines/*/runs/*/eval.md       -> Completed (verdict parsed from the file)
# Run on demand, on a /loop cadence, or from the orchestrator after each dispatch.
set -euo pipefail
cd "$(dirname "$0")/.."   # -> agent-loop/
OUT=dashboard.md
NOW=$(date "+%Y-%m-%d %H:%M")

{
  echo "# Agent-loop Dashboard"
  echo
  echo "> Generated by \`scripts/update-dashboard.sh\` — **do not hand-edit**, it is overwritten."
  echo "> Last updated: **$NOW**"
  echo

  # --- Orchestrator poll loop: alive or not? -------------------------------------
  # The tick stamps orchestrator/.heartbeat every run. Fresh stamp = the /loop poll is
  # running; a stale or missing stamp = nobody is checking the inbox right now.
  echo "## 🫀 Orchestrator loop"
  ACTIVE_WITHIN=3900   # 65 min — a 30-min /loop plus scheduler jitter still reads as active
  if [ -f orchestrator/.heartbeat ]; then
    hb=$(head -1 orchestrator/.heartbeat)
    age=$(( $(date +%s) - hb ))
    if   [ "$age" -lt 90 ];   then ago="just now"
    elif [ "$age" -lt 3600 ]; then ago="$((age / 60))m ago"
    else                           ago="$((age / 3600))h $(((age % 3600) / 60))m ago"
    fi
    if [ "$age" -lt "$ACTIVE_WITHIN" ]; then
      echo "- 🟢 **active** — last tick $ago"
    else
      echo "- ⚪ **idle** — last tick $ago (the \`/loop /orchestrate\` poll is not running)"
    fi
  else
    echo "- ⚪ **never run** — start it with \`/loop 30m /orchestrate\`"
  fi
  echo

  # --- Running: a run folder that has started but has no eval verdict yet ---
  echo "## 🔄 Running"
  running=0
  for d in pipelines/*/runs/*/; do
    [ -d "$d" ] || continue
    [ -f "${d}eval.md" ] && continue
    pipe=$(printf '%s' "$d" | cut -d/ -f2)
    run=$(basename "$d")
    echo "- \`$pipe\` · run \`$run\` — in progress"
    running=$((running + 1))
  done
  [ "$running" -eq 0 ] && echo "- _nothing running_"
  echo

  # --- Queued: inbox items waiting for the orchestrator to dispatch ---
  echo "## ⏳ Queued"
  q=0
  for f in orchestrator/inbox/*.md; do
    [ -f "$f" ] || continue
    type=$(grep -m1 '^type:' "$f" | sed 's/type:[[:space:]]*//' || echo "?")
    body=$(grep -m1 -vE '^(---|type:|priority:|created:|[[:space:]]*$)' "$f" | cut -c1-72 || true)
    echo "- **${type}** — \`$(basename "$f")\`: ${body}…"
    q=$((q + 1))
  done
  [ "$q" -eq 0 ] && echo "- _queue empty_"
  echo

  # --- Completed: a run folder with an eval verdict (newest first) ---
  echo "## ✅ Completed"
  done_any=0
  for d in $(ls -dt pipelines/*/runs/*/ 2>/dev/null); do
    [ -f "${d}eval.md" ] || continue
    pipe=$(printf '%s' "$d" | cut -d/ -f2)
    run=$(basename "$d")
    verdict=$(grep -m1 '^verdict:' "${d}eval.md" | sed 's/verdict:[[:space:]]*//' || echo "?")
    summary=$(grep -m1 -E '^(coverage|eslint|suite|mutation):' "${d}eval.md" | cut -c1-96 || true)
    icon="✅"; [ "$verdict" = "fail" ] && icon="⛔"
    if [ -n "$summary" ]; then
      echo "- ${icon} \`$pipe\` · run \`$run\` — ${verdict} (${summary})"
    else
      echo "- ${icon} \`$pipe\` · run \`$run\` — ${verdict}"
    fi
    done_any=$((done_any + 1))
  done
  [ "$done_any" -eq 0 ] && echo "- _none yet_"
  echo

  echo "---"
  echo "_Pipelines registered: $(ls -d pipelines/*/ 2>/dev/null | wc -l | tr -d ' ') · Live workflow view: \`/workflows\`_"
} > "$OUT"

echo "dashboard.md updated ($NOW)"
