import { z } from "zod";
import { idSchema, propertyIdSchema, timestampSchema, userIdSchema } from "./_common";

// Domain type for one row in the activities table.
// entity + action are plain strings (no enum), so new event types need no migration.
export const ActivitySchema = z.object({
  // UUID string generated by crypto.randomUUID() at insert time.
  id: idSchema,
  // Clerk user ID of the actor.
  userId: userIdSchema,
  // What kind of thing changed, e.g. "property", "payment", "photo".
  entity: z.string().min(1),
  // What happened, e.g. "created", "updated", "deleted".
  action: z.string().min(1),
  // The specific record id, e.g. "PROP-0001". Optional.
  entityId: z.string().optional(),
  // Short label for feeds, e.g. "property.deleted — PROP-0001".
  title: z.string().min(1),
  // Human-readable description, e.g. "Property 'Riverside Apt' archived".
  description: z.string().min(1),
  // Optional FK to properties — lets the per-property panel filter to its own events.
  propertyId: propertyIdSchema.optional(),
  // Milliseconds since epoch (converted from DB timestamp by toDomain).
  createdAt: timestampSchema,
  updatedAt: timestampSchema,
});

export type Activity = z.infer<typeof ActivitySchema>;
