export interface Property {
  id: number;
  name: string;
  code: string;
  type: "residential" | "commercial" | "multi-unit" | "retail" | "land" | "industrial" | "construction" | "other";
  province: string;
  status: "Rented" | "Vacant" | "Owner-Occupied";
  totalArea: string;
  buyNumeric: number;
  title: string;
  health: number;
  lat: number;
  lng: number;
  // Location
  addressLine?: string;
  addressLine2?: string;
  city?: string;
  country?: string;
  // Finance
  purchasePrice?: string;
  purchaseDate?: number;
  currentMarketValue?: number;
  annualPropertyTax?: number;
  annualInsurance?: number;
  ownershipStatus?: string;
  // Media
  yearBuilt?: string;
  bedrooms?: string;
  bathrooms?: string;
  parkingSpaces?: string;
}

export const properties: Property[] = [
  {
    id: 1,
    name: "Boeung Trabek Corner Building",
    code: "PP-BT-001",
    type: "commercial",
    province: "Phnom Penh",
    status: "Rented",
    totalArea: "94",
    buyNumeric: 280000,
    title: "Hard title",
    health: 88,
    lat: 11.52991,
    lng: 104.92284,
    addressLine: "No. AA21, Street 99, Boeng Trabek, Chamkar Mon",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$280,000",
    purchaseDate: Date.UTC(2020, 2, 1),
    currentMarketValue: 288000,
    annualPropertyTax: 224,
    annualInsurance: 840,
    ownershipStatus: "Owned outright",
    yearBuilt: "2008",
    parkingSpaces: "2",
  },

  // --- Olympic cluster, 215 Veal Vong, 7 Makara ---
  {
    id: 2,
    name: "Olympic Flat 172AE1",
    code: "PP-OM-001",
    type: "multi-unit",
    province: "Phnom Penh",
    status: "Vacant",
    totalArea: "65",
    buyNumeric: 65000,
    title: "Hard title",
    health: 42,
    lat: 11.55976,
    lng: 104.90782,
    addressLine: "No. 172AE1, Street 215, Veal Vong, 7 Makara",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$65,000",
    purchaseDate: Date.UTC(2019, 3, 15),
    currentMarketValue: 70000,
    annualPropertyTax: 40,
    annualInsurance: 195,
    ownershipStatus: "Owned outright",
    yearBuilt: "2012",
    bedrooms: "1",
    bathrooms: "1",
    parkingSpaces: "1",
  },
  {
    id: 3,
    name: "Olympic Studio 172BEo",
    code: "PP-OM-002",
    type: "multi-unit",
    province: "Phnom Penh",
    status: "Vacant",
    totalArea: "35",
    buyNumeric: 55000,
    title: "Hard title",
    health: 55,
    lat: 11.55976,
    lng: 104.90782,
    addressLine: "No. 172BEo, Street 215, Veal Vong, 7 Makara",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$55,000",
    purchaseDate: Date.UTC(2019, 3, 15),
    currentMarketValue: 60000,
    annualPropertyTax: 30,
    annualInsurance: 165,
    ownershipStatus: "Owned outright",
    yearBuilt: "2012",
    bedrooms: "0",
    bathrooms: "1",
    parkingSpaces: "1",
  },
  {
    id: 4,
    name: "Olympic Unit 172BE1",
    code: "PP-OM-003",
    type: "multi-unit",
    province: "Phnom Penh",
    status: "Vacant",
    totalArea: "32",
    buyNumeric: 50000,
    title: "Hard title",
    health: 60,
    lat: 11.55976,
    lng: 104.90782,
    addressLine: "No. 172BE1, Street 215, Veal Vong, 7 Makara",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$50,000",
    purchaseDate: Date.UTC(2019, 3, 15),
    currentMarketValue: 55000,
    annualPropertyTax: 25,
    annualInsurance: 150,
    ownershipStatus: "Owned outright",
    yearBuilt: "2012",
    bedrooms: "1",
    bathrooms: "1",
    parkingSpaces: "1",
  },
  {
    id: 5,
    name: "Olympic Shop 172CDE0",
    code: "PP-OM-004",
    type: "multi-unit",
    province: "Phnom Penh",
    status: "Vacant",
    totalArea: "48",
    buyNumeric: 75000,
    title: "Hard title",
    health: 48,
    lat: 11.55976,
    lng: 104.90782,
    addressLine: "No. 172CDE0, Street 215, Veal Vong, 7 Makara",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$75,000",
    purchaseDate: Date.UTC(2019, 3, 15),
    currentMarketValue: 80000,
    annualPropertyTax: 50,
    annualInsurance: 225,
    ownershipStatus: "Owned outright",
    yearBuilt: "2012",
    parkingSpaces: "1",
  },
  {
    id: 6,
    name: "Olympic Flat 172CE1",
    code: "PP-OM-005",
    type: "multi-unit",
    province: "Phnom Penh",
    status: "Vacant",
    totalArea: "32",
    buyNumeric: 50000,
    title: "Hard title",
    health: 52,
    lat: 11.55976,
    lng: 104.90782,
    addressLine: "No. 172CE1, Street 215, Veal Vong, 7 Makara",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$50,000",
    purchaseDate: Date.UTC(2019, 3, 15),
    currentMarketValue: 55000,
    annualPropertyTax: 25,
    annualInsurance: 150,
    ownershipStatus: "Owned outright",
    yearBuilt: "2012",
    bedrooms: "1",
    bathrooms: "1",
    parkingSpaces: "1",
  },
  {
    id: 7,
    name: "Olympic Unit 172DE1",
    code: "PP-OM-006",
    type: "multi-unit",
    province: "Phnom Penh",
    status: "Vacant",
    totalArea: "45",
    buyNumeric: 45000,
    title: "Hard title",
    health: 35,
    lat: 11.55976,
    lng: 104.90782,
    addressLine: "No. 172DE1, Street 215, Veal Vong, 7 Makara",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$45,000",
    purchaseDate: Date.UTC(2019, 3, 15),
    currentMarketValue: 50000,
    annualPropertyTax: 20,
    annualInsurance: 135,
    ownershipStatus: "Owned outright",
    yearBuilt: "2012",
    bedrooms: "1",
    bathrooms: "1",
    parkingSpaces: "1",
  },
  {
    id: 8,
    name: "Olympic Studio 172EE0",
    code: "PP-OM-007",
    type: "multi-unit",
    province: "Phnom Penh",
    status: "Vacant",
    totalArea: "48",
    buyNumeric: 72000,
    title: "Hard title",
    health: 50,
    lat: 11.55976,
    lng: 104.90782,
    addressLine: "No. 172EE0, Street 215, Veal Vong, 7 Makara",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$72,000",
    purchaseDate: Date.UTC(2019, 3, 15),
    currentMarketValue: 78000,
    annualPropertyTax: 47,
    annualInsurance: 216,
    ownershipStatus: "Owned outright",
    yearBuilt: "2012",
    bedrooms: "0",
    bathrooms: "1",
    parkingSpaces: "1",
  },
  {
    id: 9,
    name: "Olympic Flat 172EE1",
    code: "PP-OM-008",
    type: "multi-unit",
    province: "Phnom Penh",
    status: "Vacant",
    totalArea: "40",
    buyNumeric: 45000,
    title: "Hard title",
    health: 38,
    lat: 11.55976,
    lng: 104.90782,
    addressLine: "No. 172EE1, Street 215, Veal Vong, 7 Makara",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$45,000",
    purchaseDate: Date.UTC(2019, 3, 15),
    currentMarketValue: 50000,
    annualPropertyTax: 20,
    annualInsurance: 135,
    ownershipStatus: "Owned outright",
    yearBuilt: "2012",
    bedrooms: "1",
    bathrooms: "1",
    parkingSpaces: "1",
  },

  // --- BKK1 / Chamkar Mon ---
  {
    id: 10,
    name: "BKK1 Commercial Building 191D",
    code: "PP-BK-001",
    type: "commercial",
    province: "Phnom Penh",
    status: "Rented",
    totalArea: "172",
    buyNumeric: 950000,
    title: "Hard title",
    health: 92,
    lat: 11.55264,
    lng: 104.92383,
    addressLine: "No. 191D, Street 63, Boeung Keng Kang 1, Chamkar Mon",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$950,000",
    purchaseDate: Date.UTC(2022, 2, 4),
    currentMarketValue: 970000,
    annualPropertyTax: 760,
    annualInsurance: 2850,
    ownershipStatus: "Owned outright",
    yearBuilt: "2010",
    parkingSpaces: "3",
  },
  {
    id: 11,
    name: "BKK1 Corner Residence No.35",
    code: "PP-BK-002",
    type: "residential",
    province: "Phnom Penh",
    status: "Owner-Occupied",
    totalArea: "421",
    buyNumeric: 2100000,
    title: "Hard title",
    health: 100,
    lat: 11.55300,
    lng: 104.92400,
    addressLine: "No. 35, Street 334, Boeung Keng Kang 1, Chamkar Mon",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$2,100,000",
    purchaseDate: Date.UTC(2018, 0, 1),
    currentMarketValue: 2165000,
    annualPropertyTax: 1680,
    annualInsurance: 6300,
    ownershipStatus: "Owned outright",
    yearBuilt: "2005",
    bedrooms: "4",
    bathrooms: "3",
    parkingSpaces: "2",
  },
  {
    id: 12,
    name: "BKK1 Family Home No.223",
    code: "PP-BK-003",
    type: "residential",
    province: "Phnom Penh",
    status: "Owner-Occupied",
    totalArea: "458",
    buyNumeric: 2450000,
    title: "Hard title",
    health: 97,
    lat: 11.55350,
    lng: 104.92380,
    addressLine: "No. 223, Street 63, Boeung Keng Kang 1, Chamkar Mon",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$2,450,000",
    purchaseDate: Date.UTC(2018, 6, 1),
    currentMarketValue: 2515000,
    annualPropertyTax: 1960,
    annualInsurance: 7350,
    ownershipStatus: "Owned outright",
    yearBuilt: "2007",
    bedrooms: "5",
    bathrooms: "4",
    parkingSpaces: "2",
  },

  // --- Chak Angre / Meanchey ---
  {
    id: 13,
    name: "Chak Angre Building A",
    code: "PP-CA-001",
    type: "commercial",
    province: "Phnom Penh",
    status: "Rented",
    totalArea: "454",
    buyNumeric: 680000,
    title: "Hard title",
    health: 78,
    lat: 11.50950,
    lng: 104.92980,
    addressLine: "No. 16 (Building A), Peng Huot Road, Chak Angre Leu, Meanchey",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$680,000",
    purchaseDate: Date.UTC(2021, 0, 1),
    currentMarketValue: 690000,
    annualPropertyTax: 544,
    annualInsurance: 2040,
    ownershipStatus: "Owned outright",
    yearBuilt: "2005",
    parkingSpaces: "5",
  },
  {
    id: 14,
    name: "Chak Angre Building B",
    code: "PP-CA-002",
    type: "commercial",
    province: "Phnom Penh",
    status: "Rented",
    totalArea: "692",
    buyNumeric: 850000,
    title: "Hard title",
    health: 74,
    lat: 11.50980,
    lng: 104.93000,
    addressLine: "No. 16 (Building B), Peng Huot Road, Chak Angre Leu, Meanchey",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$850,000",
    purchaseDate: Date.UTC(2021, 5, 1),
    currentMarketValue: 868000,
    annualPropertyTax: 680,
    annualInsurance: 2550,
    ownershipStatus: "Owned outright",
    yearBuilt: "2006",
    parkingSpaces: "4",
  },
  {
    id: 15,
    name: "Chak Angre Land Plot",
    code: "PP-CA-003",
    type: "land",
    province: "Phnom Penh",
    status: "Rented",
    totalArea: "3,338",
    buyNumeric: 620000,
    title: "Soft title",
    health: 62,
    lat: 11.50800,
    lng: 104.92950,
    addressLine: "Chak Angre Leu, Meanchey (near National Road 1 overpass)",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$620,000",
    purchaseDate: Date.UTC(2022, 0, 1),
    currentMarketValue: 650000,
    annualPropertyTax: 496,
    annualInsurance: 1860,
    ownershipStatus: "Owned outright",
  },
  {
    id: 16,
    name: "Tuol Roka Land",
    code: "PP-CA-004",
    type: "land",
    province: "Phnom Penh",
    status: "Vacant",
    totalArea: "893",
    buyNumeric: 410000,
    title: "Hard title",
    health: 45,
    lat: 11.50995,
    lng: 104.92979,
    addressLine: "Tuol Roka 1, Chak Angre Leu, Meanchey",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$410,000",
    purchaseDate: Date.UTC(2023, 0, 1),
    currentMarketValue: 430000,
    annualPropertyTax: 328,
    annualInsurance: 1230,
    ownershipStatus: "Owned outright",
  },

  // --- BKK1 Villa ---
  {
    id: 17,
    name: "BKK1 Villa No.158",
    code: "PP-BK-004",
    type: "residential",
    province: "Phnom Penh",
    status: "Vacant",
    totalArea: "717",
    buyNumeric: 2800000,
    title: "Hard title",
    health: 83,
    lat: 11.54485,
    lng: 104.92290,
    addressLine: "No. 158, Street 71, Boeung Keng Kang 1, Chamkar Mon",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$2,800,000",
    purchaseDate: Date.UTC(2019, 8, 1),
    currentMarketValue: 2850000,
    annualPropertyTax: 2240,
    annualInsurance: 8400,
    ownershipStatus: "Owned outright",
    yearBuilt: "2015",
    bedrooms: "6",
    bathrooms: "5",
    parkingSpaces: "3",
  },

  // --- Condos ---
  {
    id: 18,
    name: "Camko City Condo A105",
    code: "PP-TK-001",
    type: "residential",
    province: "Phnom Penh",
    status: "Vacant",
    totalArea: "131",
    buyNumeric: 118000,
    title: "Hard title",
    health: 70,
    lat: 11.59345,
    lng: 104.89394,
    addressLine: "Unit A105-1301, Camko City, Toul Sangke, Roessei Keo",
    addressLine2: "Building 13, Floor 01",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$118,000",
    purchaseDate: Date.UTC(2020, 0, 1),
    currentMarketValue: 125000,
    annualPropertyTax: 94,
    annualInsurance: 354,
    ownershipStatus: "Owned outright",
    yearBuilt: "2016",
    bedrooms: "2",
    bathrooms: "2",
    parkingSpaces: "1",
  },
  {
    id: 19,
    name: "Samdech Pan Condo F21",
    code: "PP-DP-001",
    type: "residential",
    province: "Phnom Penh",
    status: "Vacant",
    totalArea: "84",
    buyNumeric: 87000,
    title: "Hard title",
    health: 66,
    lat: 11.56098,
    lng: 104.92380,
    addressLine: "Unit 06 F21, Samdech Pan Street 2, Boeng Raing, Daun Penh",
    addressLine2: "Floor 21",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$87,000",
    purchaseDate: Date.UTC(2021, 0, 1),
    currentMarketValue: 92000,
    annualPropertyTax: 70,
    annualInsurance: 261,
    ownershipStatus: "Owned outright",
    yearBuilt: "2014",
    bedrooms: "1",
    bathrooms: "1",
    parkingSpaces: "1",
  },

  // --- Chroy Changvar ---
  {
    id: 20,
    name: "Chroy Changvar Bridge Land",
    code: "PP-CC-001",
    type: "land",
    province: "Phnom Penh",
    status: "Vacant",
    totalArea: "17,212",
    buyNumeric: 1950000,
    title: "Hard title",
    health: 57,
    lat: 11.63512,
    lng: 104.90824,
    addressLine: "Prek Takong, Prek Tasek, Chroy Changvar",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$1,950,000",
    purchaseDate: Date.UTC(2024, 0, 17),
    currentMarketValue: 2015000,
    annualPropertyTax: 1560,
    annualInsurance: 5850,
    ownershipStatus: "Owned outright",
  },
  {
    id: 21,
    name: "Prek Leab Shophouse F153",
    code: "PP-CC-002",
    type: "retail",
    province: "Phnom Penh",
    status: "Vacant",
    totalArea: "158",
    buyNumeric: 320000,
    title: "Hard title",
    health: 72,
    lat: 11.66029,
    lng: 104.91142,
    addressLine: "No. F153, Street 6A, Prek Leab, Chroy Changvar",
    city: "Phnom Penh",
    country: "Cambodia",
    purchasePrice: "$320,000",
    purchaseDate: Date.UTC(2023, 5, 1),
    currentMarketValue: 340000,
    annualPropertyTax: 256,
    annualInsurance: 960,
    ownershipStatus: "Owned outright",
    yearBuilt: "2011",
    bedrooms: "3",
    bathrooms: "2",
    parkingSpaces: "1",
  },
];
