// General-purpose audit table. One row per user action that changes data.
//
// Why a new table instead of extending estate_activity_events?
// estate_activity_events uses a Postgres enum for its "kind" column — locked to 7 values.
// Adding new event types (payment, work-order, photo, etc.) would require a migration
// every time. Using plain text here means new event types are free.
//
// Why crypto.randomUUID() instead of the nextId counter?
// The nextId counter hits a global lock on the id_counters table. For a high-volume
// append-only log (every mutation writes here), that lock is a bottleneck. A UUID
// generated in JS is lock-free. The tradeoff: ids are not sequential or human-readable,
// but audit log rows don't need to be cross-referenced by a short code.

import { pgTable, text, timestamp, index } from "drizzle-orm/pg-core";
import { organizations } from "./identity";
import { properties } from "./property";

export const activities = pgTable(
  "activities",
  {
    // Random UUID generated by JS at insert time (via $defaultFn). Not human-readable
    // like "PROP-0001", but avoids the global id_counters lock.
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),

    // Which org this activity row belongs to. Every query filters by orgId first.
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),

    // The Clerk user ID of the person who performed the action.
    userId: text("user_id").notNull(),

    // What kind of thing changed. Plain text so no enum migration is needed for new types.
    // Examples: "property", "payment", "photo", "folder", "coOwner", "workOrder".
    entity: text("entity").notNull(),

    // What happened to it. Plain text for the same reason.
    // Examples: "created", "updated", "deleted", "added", "removed".
    action: text("action").notNull(),

    // The specific record that changed, e.g. "PROP-0001". Optional — some events
    // (like a bulk operation) don't have a single entity id.
    entityId: text("entity_id"),

    // Short label for activity feeds, e.g. "property.deleted — PROP-0001".
    title: text("title").notNull(),

    // Human-readable explanation, e.g. "Property 'Riverside Apartment' archived".
    description: text("description").notNull(),

    // Optional: which property this activity is about. Allows per-property filtering.
    // SET NULL on delete: if a property is hard-deleted the audit row survives with propertyId = null
    // rather than being deleted itself or blocking the property delete.
    propertyId: text("property_id").references(() => properties.id, { onDelete: "set null" }),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // "Show all activity for this org" — the most common query.
    index("ix_activities_org").on(t.orgId),
    // "Show all activity for this property" — used by the per-property panel.
    index("ix_activities_property").on(t.propertyId),
  ],
);
