/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user's profile
         * @description Returns the caller's own profile (email, displayName, role, orgName).
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List org properties (paginated)
         * @description Opaque-cursor page of the caller's org's properties.
         *     Pass the `nextCursor` from the previous response as the new `cursor`.
         */
        get: operations["listProperties"];
        put?: never;
        /**
         * Create a property
         * @description Creates a new property under the caller's organization.
         */
        post: operations["createProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single property's detail
         * @description Returns a property's detail DTO, scoped to the caller's org.
         */
        get: operations["getPropertyDetail"];
        put?: never;
        post?: never;
        /**
         * Delete a property
         * @description Deletes a property. Idempotent — returns 204 even if already deleted.
         */
        delete: operations["deleteProperty"];
        options?: never;
        head?: never;
        /**
         * Update a property
         * @description Partially updates a property. Any omitted field is left unchanged.
         */
        patch: operations["updateProperty"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MeDto: {
            /** Format: email */
            email: string;
            displayName: string | null;
            /** @description orgRole from the auth context */
            role: string;
            orgName: string;
        };
        PropertyListItemDtoV1: {
            id: string;
            name: string;
            /** @description Property type (e.g. apartment, house, condo) */
            type: string;
            /** @description Property status (e.g. active, inactive, cancelled) */
            status: string;
            city: string | null;
            province: string | null;
            /** @description Unix timestamp (milliseconds) */
            createdAt: number;
        };
        PropertyDetailDtoV1: {
            addressLine: string | null;
            country: string | null;
            totalArea: string;
            bedrooms: string | null;
            bathrooms: string | null;
            yearBuilt: string | null;
        } & components["schemas"]["PropertyListItemDtoV1"];
        ErrorEnvelope: {
            error: {
                /** @enum {string} */
                code: "unauthorized" | "invalid_request" | "not_found" | "rate_limited" | "internal_error";
                message: string;
            };
        };
    };
    responses: {
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Invalid query parameter or cursor */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found or not in caller's org */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Unexpected server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listProperties: {
        parameters: {
            query?: {
                /** @description Number of items per page (1-100). Defaults to 20. */
                limit?: number;
                /** @description Opaque cursor from the previous page's `nextCursor`. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated property list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["PropertyListItemDtoV1"][];
                        /** @description Cursor for the next page. Null if no more pages. */
                        nextCursor?: string | null;
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createProperty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    type: string;
                    status: string;
                    lat: number;
                    lng: number;
                    buyNumeric: number;
                    totalArea: string;
                    title: string;
                    addressLine?: string | null;
                    city?: string | null;
                    province?: string | null;
                    zip?: string | null;
                    country?: string | null;
                };
            };
        };
        responses: {
            /** @description Property created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetailDtoV1"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getPropertyDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Property ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Property detail found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetailDtoV1"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Property ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Property deleted (or already absent) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    updateProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Property ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    type?: string;
                    status?: string;
                    lat?: number;
                    lng?: number;
                    buyNumeric?: number;
                    totalArea?: string;
                    title?: string;
                    addressLine?: string | null;
                    city?: string | null;
                    province?: string | null;
                };
            };
        };
        responses: {
            /** @description Property updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetailDtoV1"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
